---
root: true
parserOptions:
  parser: babel-eslint
env:
  browser: true
extends:
  - plugin:vue/recommended
  - standard
plugins:
  - vue
rules:
  brace-style:
    - 2
    - stroustrup
  comma-dangle:
    - 2
    - always-multiline
  generator-star-spacing: 0
  no-debugger: 0
  vue/max-attributes-per-line:
    - 2
    - {singleline: 3}
